### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by OOHehir** [linux4sam/egt-thermostat#1]
Hello,
I've tried building this application as per instruction but I'm getting the error:

```
checking if libc contains libintl... yes
checking libintl.h usability... yes
checking libintl.h presence... yes
checking for libintl.h... yes
checking for LIBEGT... no
configure: error: libegt not found.  This is required.
```

For my system I'm using:

```
CXXFLAGS="-I/usr/local/include/" \
LDFLAGS="-L/usr/local/lib/" \
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig \
./configure
```

libegt.so.3.0.0 exists in /usr/local/lib

Do you have any idea what may be the issue?

Thanks,

**Comment by ldesroches** [comment]
Hello,

Does pkg-config libegt --cflags --libs work?

Regards,

**Comment by OOHehir** [comment]
Thanks for the response.

Running:

`pkg-config libegt --cflags --libs`

returns
`
-pthread -I/usr/local/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/gstreamer-1.0 -I/usr/include/lua5.3 -I/usr/include/plplot -I/usr/include/x86_64-linux-gnu -I/usr/include/librsvg-2.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -L/usr/local/lib -legt -lcairo`

**Comment by ldesroches** [comment]
Ok so it means pkg-config knows the EGT library. I am not able to reproduce your issue, are you using the latest tags for both repositories or specific versions?

**Comment by OOHehir** [comment]
For the thermostat I have v1.3:
commit 6d1809c158b43f611bbf7ac360449bb984254a07 (HEAD -> master, tag: 1.3-rc1, origin/master, origin/HEAD)

For EGT itself I have the Head dated 30th Aug:
commit 1d6289caf10cb6aedaba66ce53e4770de1483ee1 (HEAD -> master)
Author: Cyrille Pitchen <cyrille.pitchen@microchip.com>
Date:   Mon Aug 30 12:52:53 2021 -0700

**Comment by ldesroches** [comment]
Ok you need to update the EGT library. EGT thermostat requires EGT >= 1.3. Your EGT library is between 1.2 and 1.3.

**Comment by OOHehir** [comment]
Thanks, I'll try that & let you know how it goes..

**Comment by OOHehir** [comment]
I updated both EGT & this application but still getting the same build error:

```
checking for LIBEGT... no
configure: error: libegt not found.  This is required.
```

**Comment by ldesroches** [comment]
Well, honestly I don't really know what is going wrong. Does 'pkg-config libegt --modversion' return 1.3? Do you have the same issue with egt-samples?

**Comment by OOHehir** [comment]
Running pkg-config libegt --modversion returns 1.2. 
However I get:
```
git pull
Already up to date.

git branch
* master

git status
On branch master
Your branch is up to date with 'origin/master'.

git log
commit c3fbd44f583f04978b1419d190f45da6757a88b8 (HEAD -> master, origin/master, origin/HEAD)
Date:   Fri Dec 17 07:43:53 2021 +0100

    examples/basic: revert unexpected changes
    
    Revert some changes that should not have been committed.

```
I've previously built the egt examples without issue.

**Comment by ldesroches** [comment]
So there is an issue with the version of EGT installed on your machine. Either something went wrong when you installed it or there is an issue with the master branch. Please try to checkout the 1.3 tag and install EGT. It should work. Next try with master again.

**Comment by OOHehir** [comment]
Issue solved. 

My fault, apologies for the hassle. After updating EGT I omitted the 'make install' step & hence was still using the previously built library.

By the way I've created a pull request with some modifications for the Readme.md file. It helps with the paths & corrects the name of the compiled binary. Feel free to modify/reject as you see fit. 

Thanks again,
